# Name of Github Action
name: run gamescraper.py


# Controls the what will start the action. 
# For this action, action will be triggered on any push to main, and it is schedule to run at 9am daily. 
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 15 * * *" # Cron Job Scheduled At: 3:00pm UTC / 9:00am CST / 10:00am EST

# This describes the steps that will run to complete the job.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install python-version 3.10

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run gamescraper.py
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          SENDER_PASS: ${{ secrets.SENDER_PASS }}
        run: |
          python gamescraper.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
